// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdMMY_21MCaaYIWzw63WIUh6uWs5IErjg',
    appId: '1:193111462403:web:4aecb3d409727da1a63436',
    messagingSenderId: '193111462403',
    projectId: 'application-des-activites-mai',
    authDomain: 'application-des-activites-mai.firebaseapp.com',
    storageBucket: 'application-des-activites-mai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz8b7_L6dxR1qJ07w2OM-OupeAAi_kAMQ',
    appId: '1:193111462403:android:eb34b278f6aef79aa63436',
    messagingSenderId: '193111462403',
    projectId: 'application-des-activites-mai',
    storageBucket: 'application-des-activites-mai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUjWcGTJvhxfu56GcJm1vFLoXPNoUqrSc',
    appId: '1:193111462403:ios:d00131261eba9e94a63436',
    messagingSenderId: '193111462403',
    projectId: 'application-des-activites-mai',
    storageBucket: 'application-des-activites-mai.appspot.com',
    iosBundleId: 'com.example.applicationDesActivitesMai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUjWcGTJvhxfu56GcJm1vFLoXPNoUqrSc',
    appId: '1:193111462403:ios:6b13689a6683030da63436',
    messagingSenderId: '193111462403',
    projectId: 'application-des-activites-mai',
    storageBucket: 'application-des-activites-mai.appspot.com',
    iosBundleId: 'com.example.applicationDesActivitesMai.RunnerTests',
  );
}
